// Seed data – all board games with box assignments
// ean: null means not yet scanned
window.GAMES = [
  // Box A (full)
  {ean:null, namn:"Survive: Escape from Atlantis!", låda:"A", status:"full"},
  {ean:null, namn:"Francis Drake", låda:"A", status:"full"},
  {ean:null, namn:"Scotland Yard", låda:"A", status:"full"},
  {ean:null, namn:"Manhattan", låda:"A", status:"full"},
  {ean:null, namn:"Power Grid", låda:"A", status:"full"},
  {ean:null, namn:"Fast Sloths", låda:"A", status:"full"},
  {ean:null, namn:"Shogun", låda:"A", status:"full"},
  // Box B (full)
  {ean:null, namn:"Vast: The Crystal Caverns", låda:"B", status:"full"},
  {ean:null, namn:"Menara", låda:"B", status:"full"},
  {ean:null, namn:"Ave Caesar", låda:"B", status:"full"},
  {ean:null, namn:"Robo Rally", låda:"B", status:"full"},
  {ean:null, namn:"Flick 'Em Up", låda:"B", status:"full"},
  // Box C (null)
  {ean:null, namn:"Pret-à-Porter", låda:"C", status:null},
  {ean:null, namn:"Escape from the Aliens in Outer Space", låda:"C", status:null},
  {ean:null, namn:"Crisis", låda:"C", status:null},
  {ean:null, namn:"Belfort", låda:"C", status:null},
  {ean:null, namn:"Brew Crafters", låda:"C", status:null},
  {ean:null, namn:"Race to the Rhine", låda:"C", status:null},
  {ean:null, namn:"Medieval", låda:"C", status:null},
  {ean:null, namn:"Eminent Domain", låda:"C", status:null},
  {ean:null, namn:"Brass: Lancashire", låda:"C", status:null},
  {ean:null, namn:"Paris Connection", låda:"C", status:null},
  // Box D (null)
  {ean:null, namn:"Tärningar + stuff", låda:"D", status:null},
  {ean:null, namn:"The Isle of Cats", låda:"D", status:null},
  {ean:null, namn:"Sidereal Confluence", låda:"D", status:null},
  {ean:null, namn:"Village Rails", låda:"D", status:null},
  {ean:null, namn:"Switch & Signal", låda:"D", status:null},
  {ean:null, namn:"Ghost Stories", låda:"D", status:null},
  // Box E (luft)
  {ean:null, namn:"HeroQuest", låda:"E", status:"luft"},
  {ean:null, namn:"Welcome to the Dungeon", låda:"E", status:"luft"},
  {ean:null, namn:"Welcome Back to the Dungeon", låda:"E", status:"luft"},
  {ean:null, namn:"One Night Ultimate Werewolf", låda:"E", status:"luft"},
  {ean:null, namn:"The Crew: The Quest for Planet Nine", låda:"E", status:"luft"},
  {ean:null, namn:"King of Tokyo: Power Up", låda:"E", status:"luft"},
  {ean:null, namn:"King of Tokyo: Halloween", låda:"E", status:"luft"},
  {ean:null, namn:"Spartacus", låda:"E", status:"luft"},
  {ean:null, namn:"Castle Panic: The Dark Titan", låda:"E", status:"luft"},
  {ean:null, namn:"Doppelt so clever", låda:"E", status:"luft"},
  {ean:null, namn:"After the Virus", låda:"E", status:"luft"},
  {ean:null, namn:"Power Struggle", låda:"E", status:"luft"},
  {ean:null, namn:"Concordia: Salsa", låda:"E", status:"luft"},
  {ean:null, namn:"Imperia 2030", låda:"E", status:"luft"},
  {ean:null, namn:"Hive", låda:"E", status:"luft"},
  {ean:null, namn:"Hotel Mystery", låda:"E", status:"luft"},
  // Box F (luft)
  {ean:null, namn:"Kemet + expansion", låda:"F", status:"luft"},
  {ean:null, namn:"Cyclades", låda:"F", status:"luft"},
  {ean:null, namn:"Doom: The Board Game", låda:"F", status:"luft"},
  {ean:null, namn:"Bridges of Shangri-La", låda:"F", status:"luft"},
  {ean:null, namn:"Blood Bowl", låda:"F", status:"luft"},
  {ean:null, namn:"The Thing: Infection at Outpost 31", låda:"F", status:"luft"},
  // Box G (luft)
  {ean:null, namn:"Scythe + expansions", låda:"G", status:"luft"},
  {ean:null, namn:"World of Warcraft: The Board Game – expansion", låda:"G", status:"luft"},
  {ean:null, namn:"Magic: The Gathering", låda:"G", status:"luft"},
  {ean:null, namn:"Ziplockpåsar i massor", låda:"G", status:"luft"},
  {ean:null, namn:"Castle Itter", låda:"G", status:"luft"},
  // Box H (full)
  {ean:null, namn:"Parade", låda:"H", status:"full"},
  {ean:"792273251158", namn:"Don't Mess with Cthulhu", låda:"H", status:"full"},
  {ean:null, namn:"King of New York + expansion", låda:"H", status:"full"},
  {ean:null, namn:"Euphoria", låda:"H", status:"full"},
  {ean:null, namn:"Mottainai", låda:"H", status:"full"},
  {ean:null, namn:"Mord im Arosa", låda:"H", status:"full"},
  {ean:null, namn:"The Bloody Inn", låda:"H", status:"full"},
  {ean:null, namn:"Twilight Struggle", låda:"H", status:"full"},
  {ean:null, namn:"Food Chain Magnate", låda:"H", status:"full"},
  {ean:null, namn:"Legendary", låda:"H", status:"full"},
  {ean:null, namn:"Conquest of Planet Earth", låda:"H", status:"full"},
  {ean:null, namn:"Star Wars: Rebellion + expansion", låda:"H", status:"full"},
  {ean:null, namn:"Bock Rock", låda:"H", status:"full"},
  // Box I (null)
  {ean:null, namn:"Legendary – tillbehör och extra material", låda:"I", status:null},
  // Box J1 (full)
  {ean:null, namn:"Rivet Wars", låda:"J1", status:"full"},
  {ean:null, namn:"Istanbul + expansion", låda:"J1", status:"full"},
  {ean:null, namn:"Onward to Venus", låda:"J1", status:"full"},
  {ean:null, namn:"Carcassonne", låda:"J1", status:"full"},
  {ean:null, namn:"Junta: Viva el Presidente", låda:"J1", status:"full"},
  {ean:null, namn:"Courtier", låda:"J1", status:"full"},
  {ean:null, namn:"Archeos Society", låda:"J1", status:"full"},
  {ean:null, namn:"Lord of the Rings: The Card Game", låda:"J1", status:"full"},
  {ean:null, namn:"Pipeline", låda:"J1", status:"full"},
  {ean:null, namn:"A Study in Emerald (Second Edition)", låda:"J1", status:"full"},
  // Box J2 (null)
  {ean:null, namn:"Race for the Galaxy + expansion", låda:"J2", status:null},
  {ean:null, namn:"Fantasy Business", låda:"J2", status:null},
  {ean:null, namn:"Nuns on the Run", låda:"J2", status:null},
  {ean:null, namn:"Hive", låda:"J2", status:null},
  {ean:null, namn:"Gamla kortspel", låda:"J2", status:null},
  {ean:null, namn:"Dogs of War", låda:"J2", status:null},
  {ean:null, namn:"Rapido", låda:"J2", status:null},
  {ean:null, namn:"300: Earth & Water", låda:"J2", status:null},
  // Box K (full)
  {ean:null, namn:"The Rivals for Catan", låda:"K", status:"full"},
  {ean:null, namn:"Small World", låda:"K", status:"full"},
  {ean:null, namn:"Small World Underground", låda:"K", status:"full"},
  {ean:null, namn:"Small World Underground: Be Not Afraid…", låda:"K", status:"full"},
  {ean:null, namn:"Small World Underground: Spider's Web", låda:"K", status:"full"},
  {ean:null, namn:"Chimera Station", låda:"K", status:"full"},
  {ean:null, namn:"Heckmeck am Bratwurmeck", låda:"K", status:"full"},
  {ean:null, namn:"Bang! The Dice Game", låda:"K", status:"full"},
  {ean:null, namn:"Bang! The Bullet", låda:"K", status:"full"},
  {ean:null, namn:"Dixit", låda:"K", status:"full"},
  {ean:null, namn:"The Boss", låda:"K", status:"full"},
  {ean:null, namn:"Circus Flohcati", låda:"K", status:"full"},
  {ean:null, namn:"Deep Space D-6", låda:"K", status:"full"},
  {ean:null, namn:"Cash 'n Guns – expansion", låda:"K", status:"full"},
  {ean:null, namn:"Dead of Winter: A Crossroads Game", låda:"K", status:"full"},
  {ean:null, namn:"Illuminati", låda:"K", status:"full"},
  {ean:null, namn:"Operation F.A.U.S.T.", låda:"K", status:"full"},
  {ean:null, namn:"Las Vegas", låda:"K", status:"full"},
  {ean:null, namn:"Gulyabani", låda:"K", status:"full"},
  {ean:null, namn:"Lost Legacy", låda:"K", status:"full"},
  {ean:null, namn:"Abyss: Kraken", låda:"K", status:"full"},
  {ean:null, namn:"Abyss: Leviathan", låda:"K", status:"full"},
  {ean:null, namn:"Kakerlaken Poker Royal", låda:"K", status:"full"},
  // Box L (full)
  {ean:null, namn:"Lifeboat", låda:"L", status:"full"},
  {ean:null, namn:"Euphoria – expansion", låda:"L", status:"full"},
  {ean:null, namn:"Elysium", låda:"L", status:"full"},
  {ean:null, namn:"Fury of Dracula", låda:"L", status:"full"},
  {ean:null, namn:"Point Salad", låda:"L", status:"full"},
  {ean:null, namn:"Cosmic Encounter + expansions", låda:"L", status:"full"},
  {ean:null, namn:"Barcelona", låda:"L", status:"full"},
  {ean:null, namn:"Mission: Red Planet", låda:"L", status:"full"},
  {ean:null, namn:"A Game of Thrones: The Board Game", låda:"L", status:"full"},
  {ean:null, namn:"Insider", låda:"L", status:"full"},
  {ean:null, namn:"Colt Super Express", låda:"L", status:"full"},
  {ean:null, namn:"Ticket to Ride: Europe 1912", låda:"L", status:"full"},
  {ean:null, namn:"Blitz", låda:"L", status:"full"},
  {ean:null, namn:"Planet", låda:"L", status:"full"},
  // Box M (full)
  {ean:null, namn:"The Doolittle Raid", låda:"M", status:"full"},
  {ean:null, namn:"A Game of Thrones – expansion", låda:"M", status:"full"},
  {ean:null, namn:"Kick-Ass: The Board Game", låda:"M", status:"full"},
  {ean:null, namn:"Container", låda:"M", status:"full"},
  {ean:null, namn:"A Touch of Evil", låda:"M", status:"full"},
  {ean:null, namn:"Ticket to Ride", låda:"M", status:"full"},
  {ean:null, namn:"Carnival Zombie", låda:"M", status:"full"},
  {ean:null, namn:"Avalon", låda:"M", status:"full"},
  {ean:null, namn:"Exit", låda:"M", status:"full"},
  {ean:null, namn:"Lord of the Rings: The Card Game", låda:"M", status:"full"},
  {ean:null, namn:"Sky Runners", låda:"M", status:"full"},
  // Box N (null)
  {ean:null, namn:"Thunderbolt Apache Leader", låda:"N", status:null},
  {ean:null, namn:"Corsair Leader", låda:"N", status:null},
  {ean:null, namn:"RAF", låda:"N", status:null},
  {ean:null, namn:"Sherman Leader", låda:"N", status:null},
  {ean:null, namn:"Days of Ire", låda:"N", status:null},
  {ean:null, namn:"Phantom Leader", låda:"N", status:null},
  {ean:null, namn:"Fields of Fire", låda:"N", status:null},
  {ean:null, namn:"Thunder Alley", låda:"N", status:null},
  // Box O (luft)
  {ean:null, namn:"Tärningar + stuff", låda:"O", status:"luft"},
  {ean:null, namn:"The Isle of Cats", låda:"O", status:"luft"},
  {ean:null, namn:"Sidereal Confluence", låda:"O", status:"luft"},
  {ean:null, namn:"Village Rails", låda:"O", status:"luft"},
  {ean:null, namn:"Switch & Signal", låda:"O", status:"luft"},
  {ean:null, namn:"Ghost Stories", låda:"O", status:"luft"},
  {ean:null, namn:"Furnace", låda:"O", status:"luft"},
  // Box P (null)
  {ean:null, namn:"The Siege of Runedar", låda:"P", status:null},
  {ean:null, namn:"Circus Topito", låda:"P", status:null},
  {ean:null, namn:"Evil Dead: The Board Game", låda:"P", status:null},
  {ean:null, namn:"Northern Pacific", låda:"P", status:null},
  {ean:null, namn:"That's Life!", låda:"P", status:null},
  {ean:null, namn:"Beyond the Sun", låda:"P", status:null},
  {ean:"3558380029519", namn:"Hit Z Road", låda:"P", status:null},
  {ean:null, namn:"Cyclades: Titans", låda:"P", status:null},
  {ean:null, namn:"Hollywood", låda:"P", status:null},
  {ean:null, namn:"Diner", låda:"P", status:null},
  {ean:null, namn:"Uluru", låda:"P", status:null},
  {ean:null, namn:"Make 'n' Break", låda:"P", status:null},
  {ean:null, namn:"Rem Purr A", låda:"P", status:null},
  {ean:null, namn:"Yardmaster", låda:"P", status:null},
  {ean:null, namn:"Yardmaster Express", låda:"P", status:null},
  {ean:null, namn:"Millions of Dollars", låda:"P", status:null},
  {ean:null, namn:"Beasty Bar", låda:"P", status:null},
  {ean:null, namn:"Kontor", låda:"P", status:null},
  // Box Q (luft)
  {ean:null, namn:"Thurn & Taxis", låda:"Q", status:"luft"},
  {ean:null, namn:"Kick-Ass", låda:"Q", status:"luft"},
  {ean:null, namn:"Mahjong", låda:"Q", status:"luft"},
  {ean:null, namn:"Nemo's War", låda:"Q", status:"luft"},
  {ean:null, namn:"Splendor", låda:"Q", status:"luft"},
  {ean:null, namn:"Gravwell", låda:"Q", status:"luft"},
  {ean:null, namn:"Battle for Souls", låda:"Q", status:"luft"},
  {ean:null, namn:"Raccoon Tycoon", låda:"Q", status:"luft"},
  {ean:null, namn:"Innovation Deluxe", låda:"Q", status:"luft"},
  {ean:null, namn:"Déjà Vu?", låda:"Q", status:"luft"},
  {ean:null, namn:"For Sale", låda:"Q", status:"luft"},
  {ean:null, namn:"Push", låda:"Q", status:"luft"},
  {ean:null, namn:"Scout", låda:"Q", status:"luft"},
  {ean:null, namn:"The Crew: The Quest for Planet Nine", låda:"Q", status:"luft"},
  {ean:null, namn:"Deep Sea Adventure", låda:"Q", status:"luft"},
  {ean:null, namn:"Las Vegas", låda:"Q", status:"luft"},
  {ean:null, namn:"No Thanks!", låda:"Q", status:"luft"},
  // Box R (full)
  {ean:null, namn:"Marvel Legendary", låda:"R", status:"full"},
  {ean:null, namn:"Colony", låda:"R", status:"full"},
  {ean:null, namn:"Trickerion", låda:"R", status:"full"},
  {ean:null, namn:"Tiny Towns", låda:"R", status:"full"},
  {ean:null, namn:"Abyss", låda:"R", status:"full"},
  {ean:null, namn:"Caverna", låda:"R", status:"full"},
  {ean:null, namn:"Room 25", låda:"R", status:"full"},
  // Box S (null)
  {ean:null, namn:"Jorvik", låda:"S", status:null},
  {ean:null, namn:"Skyliners", låda:"S", status:null},
  {ean:null, namn:"Toledo", låda:"S", status:null},
  {ean:null, namn:"Keltis", låda:"S", status:null},
  {ean:null, namn:"Cartagena", låda:"S", status:null},
  {ean:null, namn:"Falling Sky", låda:"S", status:null},
  {ean:null, namn:"The Artemis Project", låda:"S", status:null},
  {ean:null, namn:"Raptor", låda:"S", status:null},
  {ean:null, namn:"City of Horror", låda:"S", status:null},
  {ean:null, namn:"Mall of Horror", låda:"S", status:null},
  {ean:null, namn:"The Gallerist", låda:"T", status:null},
  {ean:null, namn:"Space Hulk", låda:"T", status:null},
  {ean:null, namn:"Stronghold", låda:"T", status:null},
  {ean:null, namn:"Horrified", låda:"T", status:null},
  {ean:null, namn:"Azul", låda:"T", status:null},
  // Garderob
  {ean:null, namn:"Rising Sun", låda:"Garderob", status:null},
  {ean:null, namn:"Bandu", låda:"Garderob", status:null},
  {ean:null, namn:"Stronghold", låda:"Garderob", status:null},
  {ean:null, namn:"Carson City", låda:"Garderob", status:null},
  {ean:null, namn:"Barrage", låda:"Garderob", status:null},
  {ean:null, namn:"Kanban EV", låda:"Garderob", status:null},
  {ean:null, namn:"The Gallerist", låda:"Garderob", status:null},
  {ean:null, namn:"Imperial", låda:"Garderob", status:null},
  {ean:null, namn:"Concordia", låda:"Garderob", status:null},
  {ean:null, namn:"Coffee Traders", låda:"Garderob", status:null},
  {ean:null, namn:"Dominant Species", låda:"Garderob", status:null},
  {ean:null, namn:"Archipelago", låda:"Garderob", status:null},
  {ean:null, namn:"The Castles of Burgundy", låda:"Garderob", status:null},
  {ean:null, namn:"Roll Player", låda:"Garderob", status:null},
  {ean:null, namn:"Wonderlands War", låda:"Garderob", status:null},
  {ean:null, namn:"Sorcerer", låda:"Garderob", status:null},
  {ean:null, namn:"Smartphone Inc.", låda:"Garderob", status:null},
  {ean:null, namn:"Rebel Princess", låda:"Garderob", status:null},
  {ean:null, namn:"North American Railways", låda:"Garderob", status:null},
  {ean:null, namn:"Hamburg", låda:"Garderob", status:null},
  {ean:null, namn:"Tokyo Highway", låda:"Garderob", status:null},
  {ean:null, namn:"Septima", låda:"Garderob", status:null},
  {ean:null, namn:"Race to Moscow", låda:"Garderob", status:null},
  {ean:null, namn:"Cuba Libre", låda:"Garderob", status:null},
  {ean:null, namn:"The Thing: The Boardgame", låda:"Garderob", status:null},
  {ean:null, namn:"Jórvík", låda:"Garderob", status:null},
  {ean:null, namn:"Fliptoons", låda:"Garderob", status:null},
  {ean:null, namn:"The Lord of the Rings: The Fellowship of the Ring – Trick-Taking Game", låda:"Garderob", status:null},
  {ean:null, namn:"The Lord of the Rings: The Two Towers – Trick-Taking Game", låda:"Garderob", status:null},
  {ean:null, namn:"Ethnos: 2nd Edition", låda:"Garderob", status:null},
];
