name: Deploy Gameboxes to globbin.se

on:
  push:
    branches: [main]
    paths:
      - 'gameboxes/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./gameboxes/
          server-dir: webroots/www/gameboxes/
          exclude: |
            **/.git*
            **/.git*/**
