name: Deploy Gameboxes to globbin.se

on:
  push:
    branches: [main]
    paths:
      - 'gameboxes/**'
      - 'gameboxesscanner/**'
      - 'gameboxeslist/**'
jobs:
  deploy-overview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy overview via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: "gameboxes/*"
          target: "webroots/www/gameboxes"
          strip_components: 1

  deploy-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy scanner via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: "gameboxesscanner/*"
          target: "webroots/www/gameboxesscanner"
          strip_components: 1

  deploy-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy list via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: "gameboxeslist/*"
          target: "webroots/www/gameboxeslist"
          strip_components: 1
